categories:
  otIcons:

settings:
  otIcons.defaultIconSet:
    category: otIcons
    type: string
    default: 'FontAwesome_7'

  otIcons.iconDirectory:
    category: otIcons
    type: string
    default: 'EXT:ot_febuild/Resources/Public/Assets/Website/SVG/'

  otIcons.defaultIconStyle:
    category: otIcons
    type: string
    default: 'solid'

  otIcons.availableIconStyles:
    category: otIcons
    type: string
    default: ''

  otIcons.customMappingDirectory:
    category: otIcons
    type: string
    default: ''
